#Imports
import random
import time

#UP TO: It wasn't fair that
#If wish to add capitalization, capitalize: everything listed under . or ! or ? that was not immediately following quotation marks, as well as Elsie, Henry, Mother, Daddy, Father, Clearwater
#Adding quotation/speech marks would be harder, but so far the only thing I've added with those is Elsie Clearwater's Poisoning
#Setup
print("I am a Markov chain generator for 10 Little Figs by Rhiân Williams.")
currentWord = input("What word from the text do you want to start with? ").lower()
nextWordOptions = []
valueList = {"ten": ["little"],
              "nine": ["little"],
              "eight": ["little"],
              "seven": ["little"],
              "six": ["little"],
              "five": ["little"],
              "four": ["little"],
              "three": ["little", "days"],
              "two": ["little", "fish", "steps"],
              "only": ["one", "because"],
              "little": ["figs", "fig", "car"],
              "figs": ["are", "and"],
              "are": ["on"],
              "on": ["my", "the", "the", "stairs"],
              "my": ["tree", "little", "daddy"],
              "tree": [",", "?"],
              ",": ["i", "eyes", "and", "when", "she", "she", "but", "a", "henry", "getting", "turning", "elsie"],
              "i": ["love", "can't", "see"],
              "love": ["figs"],
              "and": ["they're", "low", "crawl", "fro", "call", "slow", "curls", "big", "what", "we", "me", "of", "pick", "got", "onto", "kicked", "so", "not", "she"],
              "they're": ["all", "just"],
              "all": ["for"],
              "just": ["for", "him"],
              "for": ["me", "a", "the", "him"],
              "me": ["!", "?", "."],
              "!": ["the", "elsie", "elsie", "her"],
              ".": ["a", "feather", "where","finches", "green", "rainbow", "wombat", "hercules", "echidna", "spotted", "is", "why", "and", "this", "every", "this", "elsie", "she", "this", "wake", "she", "race", "she", "henry", "good", "don't", "her", "elsie", "it"],
              "a": ["flying", "place", "little", "fact"],
              "flying": ["fox"],
              "fox": ["dives"],
              "dives": ["fast"],
              "fast": ["and"],
              "low": ["."],
              "where": ["oh", "did", "is"],
              "oh": ["where", "why"],
              "did": ["that", "it"],
              "that": ["fig", "it", "he", "annoyed"],
              "fig": ["go", "fall", "left", "the", "is", "for", "?", "."],
              "fall": ["?"],
              "feather": ["legged"],
              "legged": ["spiders"],
              "spiders": ["creep"],
              "creep": ["and"],
              "crawl": ["."],
              "go": ["?"],
              "one": ["little", "for", "day", "fish", "has"],
              "finches": ["hop"],
              "hop": ["from"],
              "from": ["twig", "under"],
              "twig": ["to", ".", "to"],
              "to": ["twig", "and", "dig", "find", "her", "wake", "wait", "wake", "the"],
              "green": ["ants"],
              "ants": ["hurrying"],
              "hurrying": ["to"],
              "fro": ["."],
              "rainbow": ["lorrikeets"],
              "lorrikeets": ["laugh"],
              "laugh": ["and"],
              "call": ["."],
              "wombat": ["hunts"],
              "hunts": ["for"],
              "place": ["to"],
              "dig": ["."],
              "is": ["my", "this", "too", "there"],
              "hercules": ["moth"],
              "moth": ["lands"],
              "lands": ["soft"],
              "soft": ["and"],
              "slow": ["."],
              "echidna": ["stops"],
              "stops": ["and"],
              "curls": ["up"],
              "up": ["small", "one", "her", "!", "before", "."],
              "small": ["."],
              "spotted": ["tail"],
              "tail": ["quoll"],
              "quoll": [","],
              "eyes": ["bright", "and"],
              "bright": ["and"],
              "big": ["."],
              "left": ["on"],
              "the": ["tree", "one", "last", "past", "woods", "woods", "sheets", "floor", "sheets", "bed", "side", "kitchen", "corridor", "stairs", "rest", "way", "table", "table"],
              "this": ["little", "climbing", "was", "one", "morning", "by", "was"],
              "but": ["i", "who", "it", "sat"],
              "can't": ["reach"],
              "reach": ["it"],
              "it": ["-", "wasn't", "had", "brought", "anyway", "wasn't"],
              "-": ["no", "just"],
              "no": ["not", "fig", "rain"],
              "not": ["me", "strictly", "slowing"],
              "last": ["little"],
              "too": ["high"],
              "high": ["in"],
              "in": ["the", "the"],
              "why": ["oh", "is"],
              "there": ["no", "was"],
              "who": ["is"],
              "climbing": ["out"],
              "out": ["of", "into", "of", "and", "from"],
              "of": ["the", "note", "note", "bed", "his", "the"],
              "it's": ["my"],
              "daddy": [". . ."],
              ". . .": ["and"],
              "what": ["do"],
              "do": ["i"],
              "see": ["?"],
              "we": ["will"],
              "will": ["share"],
              "share": ["it"],
              "him": ["and", "crossly", "to", ","],
              "?": ["nine", "ten", "eight", "seven", "six", "five", "four", "three", "two", "only", "it's", "but", "the"],
             "elsie": ["clearwater", "accomplished", "told", "ran", ".", "frowned"],
             "clearwater": ["woke"],
             "woke": ["up"],
             "day": ["to", ","],
             "find": ["that"],
             "wasn't": ["raining", "fair"],
             "raining": [".", "for"],
             "was": ["of", "no", "not", "already", "already"],
             "note": ["only", "to"],
             "because": ["it", "she"],
             "had": ["been", "missed", "to"],
             "been": ["raining"],
             "past": ["three"],
             "days": [","],
             "her": ["specifically", "eyes", "brother", "great", "feet", "and", "mother", "cheerfully", "father"],
             "specifically": ["because"],
             "she": ["had", "would", "rubbed", "threw", "did", "had", "reached", "got", "tumbled"],
             "red": ["fish"],
             "blue": ["fish"],
             "fish": ["two", "red", "blue", "this"],
             "car": ["one"],
             "has": ["a"],
             "missed": ["going"],
             "going": ["out"],
             "into": ["the", "the", "the"],
             "woods": [".", "after"],
             "every": ["day"],
             "when": ["there"],
             "rain": [","],
             "would": ["wander", "serve"],
             "wander": ["into"],
             "after": ["breakfast", "him"],
             "breakfast": ["and", ","],
             "pick": ["mushrooms"],
             "mushrooms": ["."],
             "morning": [",", "!"],
             "rubbed": ["her"],
             "got": ["out", "down"],
             "bed": ["to", "so", "and"],
             "wake": ["up", "up", "up"],
             "brother": ["henry"],
             "henry": [".", "in", "complained", "was"],
             "accomplished": ["this"],
             "by": ["pulling"],
             "pulling": ["on"],
             "sheets": ["of", "back"],
             "his": ["bed"],
             "so": ["that", "she"],
             "he": ["rolled", "was"],
             "rolled": ["out"],
             "onto": ["the", "the"],
             "floor": ["."],
             "threw": ["the"],
             "back": ["onto"],
             "kicked": ["henry"],
             "side": ["."],
             "strictly": ["necessary"],
             "necessary": ["as"],
             "as": ["he", "she"],
             "already": ["awake", "awake", "sitting"],
             "awake": [",", ","],
             "brought": ["her"],
             "great": ["joy"],
             "joy": ["and"],
             "anyway": ["."],
             "told": ["him"],
             "crossly": ["."],
             "wait": ["for"],
             "before": ["their", "her"],
             "their": ["mother"],
             "mother": ["would", "greeted"],
             "serve": ["them"],
             "them": ["breakfast"],
             "fact": ["that"],
             "annoyed": ["immensely"],
             "immensely": ["."],
             "i'm": ["already"],
             "complained": [","],
             "getting": ["up"],
             "race": ["you"],
             "you": ["to"],
             "kitchen": ["!"],
             "ran": ["after"],
             "turning": ["into"],
             "corridor": ["and"],
             "slowing": ["down"],
             "down": ["as", "two", ".", "at"],
             "reached": ["the"],
             "stairs": [".", ","],
             "steps": ["before"],
             "feet": ["slid"],
             "slid": ["out"],
             "under": ["her"],
             "tumbled": ["the"],
             "rest": ["of"],
             "way": ["down"],
             "sitting": ["at"],
             "at": ["the", "the"],
             "table": [".", "."],
             "good": ["morning"],
             "greeted": ["her"],
             "cheerfully": ["."],
             "don't": ["run"],
             "run": ["on"],
             "father": ["added"],
             "added": ["."],
             "frowned": ["but"],
             "sat": ["down"],
             "fair": ["that"]
  }

#Markov Chain
if currentWord in valueList:
  for i in range(330):
    nextWordOptions.extend(valueList[currentWord])
    time.sleep(0.1)
    print (currentWord, end=" ", flush = True)
    currentWord = random.choice(nextWordOptions)
    nextWordOptions = []
else:
  print("That word is not in my value list. Restart the program and try a new word.")
