valueList = {"one": ["fish", "has"],
                  "two": ["fish"],
                  "red": ["fish"],
                  "blue": ["fish"],
                  "this": ["one"],
                  "has": ["a"],
                  "a": ["little"],
                  "little": ["car"],
                  "car": ["one"],
                  "fish": ["two", "red", "blue", "this"]}
valueList = {"ten": ["little"],
              "nine": ["little"],
              "eight": ["little"],
              "seven": ["little"],
              "six": ["little"],
              "five": ["little"],
              "four": ["little"],
              "three": ["little"],
              "two": ["little"],
              "only": ["one"],
              "little": ["figs", "fig"],
              "figs": ["are", "and"],
              "are": ["on"],
              "on": ["my", "the"],
              "my": ["tree", "little", "daddy"],
              "tree": [",", "?"],
              ",": ["i", "eyes"],
              "i": ["love", "can't", "see"],
              "love": ["figs"],
              "and": ["they're", "low", "crawl", "fro", "call", "slow", "curls", "big", "what", "we", "me"],
              "they're": ["all", "just"],
              "all": ["for"],
              "just": ["for", "him"],
              "for": ["me", "a"],
              "me": ["!", "?", "."],
              "!": ["the"],
              ".": ["a", "feather", "where","finches", "green", "rainbow", "wombat", "hercules", "echidna", "spotted", "is", "why", "and"],
              "a": ["flying", "place"],
              "flying": ["fox"],
              "fox": ["dives"],
              "dives": ["fast"],
              "fast": ["and"],
              "low": ["."],
              "where": ["oh", "did", "is"],
              "oh": ["where", "why"],
              "did": ["that"],
              "that": ["fig"],
              "fig": ["go", "fall", "left", "the", "is", "for", "?", "."],
              "fall": ["?"],
              "feather": ["legged"],
              "legged": ["spiders"],
              "spiders": ["creep"],
              "creep": ["and"],
              "crawl": ["."],
              "go": ["?"],
              "one": ["little", "for"],
              "finches": ["hop"],
              "hop": ["from"],
              "from": ["twig"],
              "twig": ["to", ".", "to"],
              "to": ["twig", "and", "dig"],
              "green": ["ants"],
              "ants": ["hurrying"],
              "hurrying": ["to"],
              "fro": ["."],
              "rainbow": ["lorrikeets"],
              "lorrikeets": ["laugh"],
              "laugh": ["and"],
              "call": ["."],
              "wombat": ["hunts"],
              "hunts": ["for"],
              "place": ["to"],
              "dig": ["."],
              "is": ["my", "this", "too", "there"],
              "hercules": ["moth"],
              "moth": ["lands"],
              "lands": ["soft"],
              "soft": ["and"],
              "slow": ["."],
              "echidna": ["stops"],
              "stops": ["and"],
              "curls": ["up"],
              "up": ["small"],
              "small": ["."],
              "spotted": ["tail"],
              "tail": ["quoll"],
              "quoll": [","],
              "eyes": ["bright"],
              "bright": ["and"],
              "big": ["."],
              "left": ["on"],
              "the": ["tree", "one", "last"],
              "this": ["little", "climbing"],
              "but": ["i", "who"],
              "can't": ["reach"],
              "reach": ["it"],
              "it": ["-"],
              "-": ["no", "just"],
              "no": ["not", "fig"],
              "not": ["me"],
              "last": ["little"],
              "too": ["high"],
              "high": ["in"],
              "in": ["the"],
              "why": ["oh", "is"],
              "there": ["no"],
              "who": ["is"],
              "climbing": ["out"],
              "out": ["of"],
              "of": ["the"],
              "it's": ["my"],
              "daddy": [". . ."],
              ". . .": ["and"],
              "what": ["do"],
              "do": ["i"],
              "see": ["?"],
              "we": ["will"],
              "will": ["share"],
              "share": ["it"],
              "him": ["and"],
              "?": ["nine", "ten", "eight", "seven", "six", "five", "four", "three", "two", "only", "it's", "but", "the"],
  }
